name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]

env:
  APP_LOCATION: "/"                # Location of your client code relative to repo root
  API_LOCATION: "api"              # Location of your API source code, if any
  APP_ARTIFACT_LOCATION: "build"   # Location of your client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read               # For actions/checkout
      pull-requests: write         # For commenting on PRs
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}

  close_pull_request_job:
    name: Close Pull Request Job
    runs-on: ubuntu-latest
    permissions:
      contents: none
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
